#!/bin/bash
git init -qqq
git remote add origin https://github.com/nguyentrunghieu98/docker-magento2.4.x
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.vscode ./
rm -rf compose .git
git init
